name: ptyrad
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - accelerate
  - h5py
  - jupyter
  - matplotlib
  - optuna
  - python
  - pytorch
  - pytorch-cuda
  - scikit-learn
  - scipy
  - tifffile
  - torchvision